export default () => [
  ['am', 'look', 'I', 'little', 'big'],
  ['here', 'big', 'Mum', 'Dad', 'little', 'is'],
  ['up', 'is', 'like', 'down', 'Dad', 'see'],
  ['Mum', 'the', 'me', 'and', 'he'],
  ['she', 'on', 'went', 'like', 'in', 'down'],
  ['got', 'me', 'the', 'comes', 'a', 'said'],
  ['put', 'go', 'comes', 'some', 'went', 'we', 'like'],
  ['where', 'his', 'said', 'my', 'this', 'comes'],
  ['see', 'Dad', 'is', 'in', 'said', 'one', 'down', 'like', 'and', 'two', 'a', 'he', 'up', 'the', 'she', 'on', 'comes', 'me', 'went', 'got', 'Mum', 'I', 'look', 'here', 'am', 'big', 'little'],
  ['said', 'put', 'we', 'go', 'where', 'some'],
  ['my', 'her', 'this', 'one', 'his', 'has'],
  ['all', 'put', 'this', 'can', 'did', 'been', 'some'],
  ['had', 'was', 'make', 'three', 'into', 'two'],
  ['are', 'went', 'where', 'first', 'came', 'can'],
  ['them', 'to', 'right', 'will', 'make'],
  ['a', 'no', 'you', 'an', 'go', 'be', 'is'],
  ['new', 'that', 'old', 'will', 'yes', 'who', 'off', 'got'],
  ['said', 'can', 'this', 'some', 'are', 'has', 'into', 'came', 'did', 'was', 'that', 'been', 'no', 'go', 'had', 'will', 'be', 'is', 'put', 'them', 'you', 'make'],
  ['do', 'right', 'there', 'old', 'out', 'will', 'for', 'that', 'wakes'],
  ['they', 'new', 'be', 'him', 'play', 'yes', 'for', 'with'],
  ['today', 'all', 'some', 'first', 'four', 'there', 'play', 'been', 'five', 'over', 'them', 'off'],
  ['before', 'not', 'him', 'other', 'made', 'your', 'has', 'some'],
  ['from', 'been', 'what', 'by', 'or', 'so', 'if', 'they', 'of', 'get', 'at', 'up'],
  ['then', 'must', 'now', 'be', 'as', 'you', 'was', 'get'],
  ['but', 'his', 'have', 'had', 'it', 'said', 'when', 'will'],
  ['their', 'more', 'back', 'of', 'call', 'it', 'see', 'all'],
  ['about', 'much', 'the', 'our', 'in', 'want', 'have', 'well', 'your'],
  ['were', 'you', 'our', 'just', 'only', 'your', 'there', 'could'],
  ['should', 'went', 'want', 'which', 'boy', 'out', 'right', 'girl'],
  ['were', 'words', 'as', 'use', 'each', 'how', 'many', 'these', 'other', 'would'],
  ['number', 'with', 'they', 'no', 'use', 'or', 'if', 'their', 'which', 'write', 'were'],
  ['way', 'before', 'people', 'than', 'over', 'water', 'called', 'new', 'our']
]
